const ACTION_UNDO = 1,
      ACTION_SKIP = 2,
      ACTION_LIST = 3,
      ACTION_UNLOAD_TAB = 4,
      ACTION_UNLOAD_WINDOW = 5,
      ACTION_UNLOAD_ALL = 6,
      // ACTION_FREEZE = 6,
      // ACTION_PROTECT = 7;
      ACTIONPROPS = {};

ACTIONPROPS[ACTION_SKIP] = "skip";
// ACTIONPROPS[ACTION_FREEZE] = "freeze";
// ACTIONPROPS[ACTION_PROTECT] = "protect";
      
